Repository kookmin-sw/capstone-2021-23, pull requests merged in 2021-05, with the labels that each got.

#33 Gstreamer test
  README.md
  _config.yml
  board/src/gstreamer_test/CLI_receive.sh
  board/src/gstreamer_test/CLI_send.sh
  board/src/gstreamer_test/opencv_class_example.py
  board/src/gstreamer_test/opencv_send.py
  board/src/gstreamer_test/opencv_udp_10000.py
  board/src/gstreamer_test/opencv_udp_5000.py
  board/src/gstreamer_test/opencv_webcam.py
  docs/23조_중간발표자료.pdf
  docs/23조_중간발표자료_v2.pdf
Labels: board, streaming

#40 [ 모델 ] ai server file 작성
  model/ai_server/video_5second_saver.py
Labels: server

#41 kakao notification
  server/notification/kakao/README.md
  server/notification/kakao/kakao_msg.py
  server/notification/kakao/kakao_token.json
  server/notification/kakao/kakao_token.py
Labels: notification, server

#43 Basic server
  capstone_project/mysite/cctv/migrations/__init__.py
  mysite/cctv/.views.py.swp
  mysite/cctv/__init__.py
  mysite/cctv/__pycache__/__init__.cpython-35.pyc
  mysite/cctv/__pycache__/__init__.cpython-37.pyc
  mysite/cctv/__pycache__/__init__.cpython-38.pyc
  mysite/cctv/__pycache__/__init__.cpython-39.pyc
  mysite/cctv/__pycache__/admin.cpython-37.pyc
  mysite/cctv/__pycache__/apps.cpython-37.pyc
  mysite/cctv/__pycache__/models.cpython-37.pyc
  mysite/cctv/__pycache__/urls.cpython-35.pyc
  mysite/cctv/__pycache__/urls.cpython-37.pyc
  mysite/cctv/__pycache__/urls.cpython-38.pyc
  mysite/cctv/__pycache__/urls.cpython-39.pyc
  mysite/cctv/__pycache__/views.cpython-35.pyc
  mysite/cctv/__pycache__/views.cpython-37.pyc
  mysite/cctv/__pycache__/views.cpython-38.pyc
  mysite/cctv/__pycache__/views.cpython-39.pyc
  mysite/cctv/admin.py
  mysite/cctv/apps.py
  mysite/cctv/camera.py
  mysite/cctv/camera.pyc
  mysite/cctv/haarcascade_frontalface_alt2.xml
  mysite/cctv/migrations/__init__.py
  mysite/cctv/migrations/__pycache__/__init__.cpython-37.pyc
  mysite/cctv/models.py
  mysite/cctv/tests.py
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/cctv/views2.py
  mysite/cctv/views3.py
  mysite/db.sqlite3
  mysite/manage.py
  mysite/mysite/__init__.py
  mysite/mysite/__pycache__/__init__.cpython-35.pyc
  mysite/mysite/__pycache__/__init__.cpython-37.pyc
  mysite/mysite/__pycache__/__init__.cpython-38.pyc
  mysite/mysite/__pycache__/__init__.cpython-39.pyc
  mysite/mysite/__pycache__/settings.cpython-35.pyc
  mysite/mysite/__pycache__/settings.cpython-37.pyc
  mysite/mysite/__pycache__/settings.cpython-38.pyc
  mysite/mysite/__pycache__/settings.cpython-39.pyc
  mysite/mysite/__pycache__/urls.cpython-35.pyc
  mysite/mysite/__pycache__/urls.cpython-37.pyc
  mysite/mysite/__pycache__/urls.cpython-38.pyc
  mysite/mysite/__pycache__/urls.cpython-39.pyc
  mysite/mysite/__pycache__/wsgi.cpython-35.pyc
  mysite/mysite/__pycache__/wsgi.cpython-37.pyc
  mysite/mysite/__pycache__/wsgi.cpython-38.pyc
  mysite/mysite/__pycache__/wsgi.cpython-39.pyc
  mysite/mysite/asgi.py
  mysite/mysite/settings.py
  mysite/mysite/urls.py
  mysite/mysite/wsgi.py
  mysite/templates/cctv/index.html
Labels: server

#45 Notification
  .gitignore
  server/notification/gmail/gmail_send.py
Labels: notification, server

#49 Basic server
  mysite/cctv/__pycache__/views.cpython-37.pyc
  mysite/cctv/views.py
Labels: server, streaming

#50 [Server] server/notification -> mysite/notification
  .gitignore
  mysite/notification/gmail/gmail_send.py
  mysite/notification/kakao/README.md
  mysite/notification/kakao/kakao_msg.py
  mysite/notification/kakao/kakao_token.py
Labels: notification, server

#51 [ Model ] Ai server directory added
  model/ai_server/client.py
  model/ai_server/inference_server.py
  model/ai_server/video_5second_saver.py
  model/ai_server/video_socket.py
  model/dataManageTools/lossDraw.py
Labels: server

#53 version 1
  .gitignore
  mysite/cctv/.views.py.swp
  mysite/cctv/__init__.py
  mysite/cctv/__pycache__/__init__.cpython-35.pyc
  mysite/cctv/__pycache__/__init__.cpython-37.pyc
  mysite/cctv/__pycache__/__init__.cpython-38.pyc
  mysite/cctv/__pycache__/__init__.cpython-39.pyc
  mysite/cctv/__pycache__/admin.cpython-37.pyc
  mysite/cctv/__pycache__/apps.cpython-37.pyc
  mysite/cctv/__pycache__/models.cpython-37.pyc
  mysite/cctv/__pycache__/urls.cpython-35.pyc
  mysite/cctv/__pycache__/urls.cpython-37.pyc
  mysite/cctv/__pycache__/urls.cpython-38.pyc
  mysite/cctv/__pycache__/urls.cpython-39.pyc
  mysite/cctv/__pycache__/views.cpython-35.pyc
  mysite/cctv/__pycache__/views.cpython-37.pyc
  mysite/cctv/__pycache__/views.cpython-38.pyc
  mysite/cctv/__pycache__/views.cpython-39.pyc
  mysite/cctv/admin.py
  mysite/cctv/apps.py
  mysite/cctv/camera.py
  mysite/cctv/camera.pyc
  mysite/cctv/haarcascade_frontalface_alt2.xml
  mysite/cctv/migrations/__init__.py
  mysite/cctv/migrations/__pycache__/__init__.cpython-37.pyc
  mysite/cctv/models.py
  mysite/cctv/tests.py
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/cctv/views2.py
  mysite/cctv/views3.py
  mysite/db.sqlite3
  mysite/manage.py
  mysite/mysite/__init__.py
  mysite/mysite/__pycache__/__init__.cpython-35.pyc
  mysite/mysite/__pycache__/__init__.cpython-37.pyc
  mysite/mysite/__pycache__/__init__.cpython-38.pyc
  mysite/mysite/__pycache__/__init__.cpython-39.pyc
  mysite/mysite/__pycache__/settings.cpython-35.pyc
  mysite/mysite/__pycache__/settings.cpython-37.pyc
  mysite/mysite/__pycache__/settings.cpython-38.pyc
  mysite/mysite/__pycache__/settings.cpython-39.pyc
  mysite/mysite/__pycache__/urls.cpython-35.pyc
  mysite/mysite/__pycache__/urls.cpython-37.pyc
  mysite/mysite/__pycache__/urls.cpython-38.pyc
  mysite/mysite/__pycache__/urls.cpython-39.pyc
  mysite/mysite/__pycache__/wsgi.cpython-35.pyc
  mysite/mysite/__pycache__/wsgi.cpython-37.pyc
  mysite/mysite/__pycache__/wsgi.cpython-38.pyc
  mysite/mysite/__pycache__/wsgi.cpython-39.pyc
  mysite/mysite/asgi.py
  mysite/mysite/settings.py
  mysite/mysite/urls.py
  mysite/mysite/wsgi.py
  mysite/notification/gmail/gmail_send.py
  mysite/notification/kakao/README.md
  mysite/notification/kakao/kakao_msg.py
  mysite/notification/kakao/kakao_token.py
  mysite/templates/cctv/index.html
Labels: server, streaming

#58 Kakao login
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/mysite/settings.py
  mysite/mysite/urls.py
  mysite/templates/cctv/index.html
Labels: server

#59 Kakao login
  mysite/mysite/urls.py
  mysite/templates/users/login.html
  mysite/users/__init__.py
  mysite/users/__pycache__/__init__.cpython-37.pyc
  mysite/users/__pycache__/admin.cpython-37.pyc
  mysite/users/__pycache__/apps.cpython-37.pyc
  mysite/users/__pycache__/exception.cpython-37.pyc
  mysite/users/__pycache__/models.cpython-37.pyc
  mysite/users/__pycache__/urls.cpython-37.pyc
  mysite/users/__pycache__/views.cpython-37.pyc
  mysite/users/admin.py
  mysite/users/apps.py
  mysite/users/exception.py
  mysite/users/migrations/__init__.py
  mysite/users/migrations/__pycache__/__init__.cpython-37.pyc
  mysite/users/models.py
  mysite/users/tests.py
  mysite/users/urls.py
  mysite/users/views.py
Labels: kakao_login

#57 Version1 improved
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/mysite/urls.py
  mysite/templates/cctv/index.html
Labels: server

#61 Kakao login and create user DB
  mysite/cctv/__pycache__/urls.cpython-37.pyc
  mysite/cctv/__pycache__/views.cpython-37.pyc
  mysite/cctv/views.py
  mysite/db.sqlite3
  mysite/mysite/__pycache__/settings.cpython-37.pyc
  mysite/mysite/__pycache__/urls.cpython-37.pyc~HEAD
  mysite/mysite/settings.py
  mysite/users/__pycache__/models.cpython-37.pyc
  mysite/users/__pycache__/urls.cpython-37.pyc
  mysite/users/__pycache__/views.cpython-37.pyc
  mysite/users/migrations/0001_initial.py
  mysite/users/migrations/0002_alter_account_user_id.py
  mysite/users/migrations/__pycache__/0001_initial.cpython-37.pyc
  mysite/users/migrations/__pycache__/0002_alter_account_user_id.cpython-37.pyc
  mysite/users/models.py
  mysite/users/urls.py
  mysite/users/views.py
Labels: kakao_login, server

#62 error fixed
  mysite/cctv/.views.py.swp
  mysite/cctv/__pycache__/urls.cpython-37.pyc
  mysite/cctv/__pycache__/views.cpython-37.pyc
  mysite/cctv/views.py
  mysite/cctv/views2.py
  mysite/cctv/views3.py
  mysite/mysite/__pycache__/settings.cpython-37.pyc
  mysite/mysite/__pycache__/urls.cpython-37.pyc
  mysite/mysite/settings.py
  mysite/users/__pycache__/models.cpython-37.pyc
  mysite/users/__pycache__/urls.cpython-37.pyc
  mysite/users/__pycache__/views.cpython-37.pyc
  mysite/users/urls.py
  mysite/users/views.py
Labels: server

#64 [ Model ] inference Threshold and mp3 play
  model/ai_server/inference_server.py
  model/ai_server/notice.sh
Labels: board

#69 Kakao login 마무리 & User Table 수정
  mysite/users/admin.py
  mysite/users/models.py
Labels: Database, kakao_login, server

#73 Cctv db설정
  mysite/cctv/admin.py
  mysite/cctv/models.py
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/users/admin.py
  mysite/users/models.py
Labels: Database, server

#87 send email
  mysite/users/urls.py
  mysite/users/views.py
Labels: server

#88 Mysite version1 improved
  mysite/cctv/.views.py.swp
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/mysite/urls.py
  mysite/templates/cctv/index.html
Labels: server

#94 Cctv db
  mysite/cctv/admin.py
  mysite/cctv/models.py
  mysite/cctv/urls.py
  mysite/db.sqlite3
  mysite/mysite/settings.py
  mysite/templates/cctv/index.html
  mysite/templates/cctv/main.html
  mysite/templates/cctv/select_cctv.html
Labels: server

#95 Cctv db
  mysite/cctv/admin.py
  mysite/cctv/models.py
  mysite/cctv/urls.py
  mysite/cctv/views.py
  mysite/db.sqlite3
  mysite/mysite/settings.py
  mysite/templates/cctv/index.html
  mysite/templates/cctv/main.html
  mysite/templates/cctv/select_cctv.html
  mysite/users/admin.py
Labels: server

#97 Cctv db
  mysite/users/admin.py
  mysite/users/models.py
  mysite/users/views.py
Labels: server

#98 Cctv db
  mysite/users/models.py
  mysite/users/views.py
Labels: server

#99 gstreamer pipeline 수정, 녹화 영상목록 template에 띄우기
  mysite/cctv/views.py
Labels: server

#100 Cctv db
  mysite/cctv/views.py
Labels: server

#101 remove file that are no longer in use
  mysite/notification/bootstrap/css/bootstrap-grid.css
  mysite/notification/bootstrap/css/bootstrap-grid.css.map
  mysite/notification/bootstrap/css/bootstrap-grid.min.css
  mysite/notification/bootstrap/css/bootstrap-grid.min.css.map
  mysite/notification/bootstrap/css/bootstrap-reboot.css
  mysite/notification/bootstrap/css/bootstrap-reboot.css.map
  mysite/notification/bootstrap/css/bootstrap-reboot.min.css
  mysite/notification/bootstrap/css/bootstrap-reboot.min.css.map
  mysite/notification/bootstrap/css/bootstrap.css
  mysite/notification/bootstrap/css/bootstrap.css.map
  mysite/notification/bootstrap/css/bootstrap.min.css
  mysite/notification/bootstrap/css/bootstrap.min.css.map
  mysite/notification/bootstrap/js/bootstrap.bundle.js
  mysite/notification/bootstrap/js/bootstrap.bundle.js.map
  mysite/notification/bootstrap/js/bootstrap.bundle.min.js
  mysite/notification/bootstrap/js/bootstrap.bundle.min.js.map
  mysite/notification/bootstrap/js/bootstrap.js
  mysite/notification/bootstrap/js/bootstrap.js.map
  mysite/notification/bootstrap/js/bootstrap.min.js
  mysite/notification/bootstrap/js/bootstrap.min.js.map
  mysite/notification/bootstrap_template/assets/favicon.ico
  mysite/notification/bootstrap_template/assets/img/avataaars.svg
  mysite/notification/bootstrap_template/assets/img/portfolio/cabin.png
  mysite/notification/bootstrap_template/assets/img/portfolio/cake.png
  mysite/notification/bootstrap_template/assets/img/portfolio/circus.png
  mysite/notification/bootstrap_template/assets/img/portfolio/game.png
  mysite/notification/bootstrap_template/assets/img/portfolio/safe.png
  mysite/notification/bootstrap_template/assets/img/portfolio/submarine.png
  mysite/notification/bootstrap_template/css/styles.css
  mysite/notification/bootstrap_template/index.html
  mysite/notification/bootstrap_template/js/scripts.js
Labels: server

#102 remove files
  mysite/notification/website_html/css/bootstrap-grid.css
  mysite/notification/website_html/css/bootstrap-grid.css.map
  mysite/notification/website_html/css/bootstrap-grid.min.css
  mysite/notification/website_html/css/bootstrap-grid.min.css.map
  mysite/notification/website_html/css/bootstrap-reboot.css
  mysite/notification/website_html/css/bootstrap-reboot.css.map
  mysite/notification/website_html/css/bootstrap-reboot.min.css
  mysite/notification/website_html/css/bootstrap-reboot.min.css.map
  mysite/notification/website_html/css/bootstrap.css
  mysite/notification/website_html/css/bootstrap.css.map
  mysite/notification/website_html/css/bootstrap.min.css
  mysite/notification/website_html/css/bootstrap.min.css.map
  mysite/notification/website_html/index.html
  mysite/notification/website_html/js/bootstrap.bundle.js
  mysite/notification/website_html/js/bootstrap.bundle.js.map
  mysite/notification/website_html/js/bootstrap.bundle.min.js
  mysite/notification/website_html/js/bootstrap.bundle.min.js.map
  mysite/notification/website_html/js/bootstrap.js
  mysite/notification/website_html/js/bootstrap.js.map
  mysite/notification/website_html/js/bootstrap.min.js
  mysite/notification/website_html/js/bootstrap.min.js.map
Labels: server

#103 Notification
  mysite/notification/bootstrap/css/bootstrap-grid.css
  mysite/notification/bootstrap/css/bootstrap-grid.css.map
  mysite/notification/bootstrap/css/bootstrap-grid.min.css
  mysite/notification/bootstrap/css/bootstrap-grid.min.css.map
  mysite/notification/bootstrap/css/bootstrap-reboot.css
  mysite/notification/bootstrap/css/bootstrap-reboot.css.map
  mysite/notification/bootstrap/css/bootstrap-reboot.min.css
  mysite/notification/bootstrap/css/bootstrap-reboot.min.css.map
  mysite/notification/bootstrap/css/bootstrap.css
  mysite/notification/bootstrap/css/bootstrap.css.map
  mysite/notification/bootstrap/css/bootstrap.min.css
  mysite/notification/bootstrap/css/bootstrap.min.css.map
  mysite/notification/bootstrap/js/bootstrap.bundle.js
  mysite/notification/bootstrap/js/bootstrap.bundle.js.map
  mysite/notification/bootstrap/js/bootstrap.bundle.min.js
  mysite/notification/bootstrap/js/bootstrap.bundle.min.js.map
  mysite/notification/bootstrap/js/bootstrap.js
  mysite/notification/bootstrap/js/bootstrap.js.map
  mysite/notification/bootstrap/js/bootstrap.min.js
  mysite/notification/bootstrap/js/bootstrap.min.js.map
  mysite/notification/bootstrap_template/assets/favicon.ico
  mysite/notification/bootstrap_template/assets/img/avataaars.svg
  mysite/notification/bootstrap_template/assets/img/portfolio/cabin.png
  mysite/notification/bootstrap_template/assets/img/portfolio/cake.png
  mysite/notification/bootstrap_template/assets/img/portfolio/circus.png
  mysite/notification/bootstrap_template/assets/img/portfolio/game.png
  mysite/notification/bootstrap_template/assets/img/portfolio/safe.png
  mysite/notification/bootstrap_template/assets/img/portfolio/submarine.png
  mysite/notification/bootstrap_template/css/styles.css
  mysite/notification/bootstrap_template/index.html
  mysite/notification/bootstrap_template/js/scripts.js
  mysite/notification/website_html/css/bootstrap-grid.css
  mysite/notification/website_html/css/bootstrap-grid.css.map
  mysite/notification/website_html/css/bootstrap-grid.min.css
  mysite/notification/website_html/css/bootstrap-grid.min.css.map
  mysite/notification/website_html/css/bootstrap-reboot.css
  mysite/notification/website_html/css/bootstrap-reboot.css.map
  mysite/notification/website_html/css/bootstrap-reboot.min.css
  mysite/notification/website_html/css/bootstrap-reboot.min.css.map
  mysite/notification/website_html/css/bootstrap.css
  mysite/notification/website_html/css/bootstrap.css.map
  mysite/notification/website_html/css/bootstrap.min.css
  mysite/notification/website_html/css/bootstrap.min.css.map
  mysite/notification/website_html/index.html
  mysite/notification/website_html/js/bootstrap.bundle.js
  mysite/notification/website_html/js/bootstrap.bundle.js.map
  mysite/notification/website_html/js/bootstrap.bundle.min.js
  mysite/notification/website_html/js/bootstrap.bundle.min.js.map
  mysite/notification/website_html/js/bootstrap.js
  mysite/notification/website_html/js/bootstrap.js.map
  mysite/notification/website_html/js/bootstrap.min.js
  mysite/notification/website_html/js/bootstrap.min.js.map
Labels: server
